### ISSUE TITLE
README.md: broken link

### ISSUE THREAD

**Issue by cznic** [rsc/getopt#1] opened 2017-08-11 08:54 UTC
> [For full package documentation, see https://godoc.org/rsc.io/getopt.]

At 10:51, Friday, 11 August 2017 (CEST) the site response after about a minute is

```
Internal server error.
```

**Comment by dmitshur** [comment] 2017-08-11 14:09
Duplicate of https://github.com/golang/gddo/issues/502.

**Comment by rsc** [comment] 2017-08-11 14:19
Closed as duplicate. Thanks @shurcooL.

**Closed as completed by rsc** 2017-08-11 14:19 UTC
